resources/views/default/form/element/images.blade.php

Added a quick validation for empty objects on images.blade.php when using the form element images. In the old way if the object returned [] i've get errors saying that implode cant do nothing and form dont show.

Added validation For empty objects on images.blade.php

---

src/Display/Column/Email.php
src/Display/Column/NamedColumn.php
src/Display/Column/RelatedLink.php
src/Display/Column/Url.php
src/Form/Element/MultiSelect.php
src/Form/Element/Select.php
src/Traits/SqlQueryOperators.php

Может понадобиться при реализации админпанелеей к закрытым клубам - в которых членство выдается один раз.
пример:
```php
AdminFormElement::multiselect('users', 'Пользователи')
->setModelForOptions(new User())
->setEmptyRelation(true)
->setDisplay('full_name')
```
```php
AdminFormElement::multiselect('users', 'Пользователи')
->setModelForOptions(new User())
->setEmptyRelation(false)
->setDisplay('full_name')
```
По умолчанию: **false**

Возможность добавлять Select/MultiSelect с опциями без Relation.

---

src/Providers/AdminServiceProvider.php

When extending any of your Display/Column or Form/Element classes inside a folder that is being autoloaded, your code tried to require them again, causing a "Cannot redeclare class" error. This should fix the issue.
If you don't understand what I'm saying, checkout my "lurk" project ("admin-sample" branch). Under "app/Admin/Addons/Display/Column/Hash.php" you can find my custom Display/Column class.
(PS: I also adapted some of your english on my project. Feel free to copy it.)

Require files bugfix

---

resources/views/default/form/buttons.blade.php

Little fix empty dropdown menu if you use `$form->getButtons()->hideSaveAndCloseButton()->hideSaveAndCreateButton();` 
P.S. Только кнопка сохранения нужна для страниц настроек, например. Да и в любом случае, если не так, то как-нибудь лучше это исправить, чтобы не заменять вручную всю вьюшку на свою при необходимости.

Fix empty button dropdown

---

src/Form/Element/Select.php

Add callback for prepare load options Query.
**Example:**
Get all options, only 'column' is 'value' and 'owner_id' is Current User id:
```php
AdminFormElement::select('column', 'Label')
->modelForOptions(MyModel::class)
->setLoadOptionsQueryPreparer(function($item, QueryBuilder $query) {
return $query
->where('column', 'value')
->were('owner_id', Auth::user()->id)
});
```

Add callback for prepare load options Query.

---

src/Form/Element/NamedFormElement.php

After updating I noticed that I still got errors when saving a (MorphOne) relationship. The error stated that the create function required an array parameter but got NULL. This pull request fixes this and add's MorphOne support to the NamedFormElement save function...

Add support for MorphOne and fix exception when saving relationship

---

src/Display/DisplayDatatablesAsync.php

Если в таблице есть поля типа `SleepingOwl\Admin\Display\Column\Text`, то даже при пустом введенном поле поиска, для них будет строиться поисковый запрос вида `where ("text_field_1" like '%%' or "text_field_2" like '%%')`.
Возможно так же стоит добавить поиск по полям типа `Link`, `RelatedLink`, `Email` и `Lists`, так как они в принципе тоже являются текстовыми.

DatatablesAsync: Строка поиска может быть пустой

---

src/Navigation/Page.php

Previous id detection didn't allow to use one model on several section pages.

Use alias insteadof model name as page id in case id is absent

---

resources/views/default/form/element/errors.blade.php
src/Traits/FormElements.php

Providing custom validation messages via required(), addValidationRule() didn't work.
It caused by mismatching class types when trying to retrieve messages.
Also, I had changed blade template to be able to output messages with markup, sometimes you need to make some parts of text bolder or italic.

fix problem with custom validation messages

---

src/Display/Column/Custom.php
src/Display/DisplayDatatablesAsync.php

In the old datatables model only named columns can be ordered, but some custom columns can also be ordered, I think it's a very useful feature.
e.g. a column name is `author_id`, use 
```php
AdminColumn::custom()->setLabel('author')->setCallback(function ($model) {
return $model->author->name;
})->setOrderField('author_id'),
```
then when we can toggle order for the author column order by author_id

make custom column orderable

---

resources/views/default/display/extensions/columns.blade.php

laravel 5.3 has no \Illuminate\Pagination\BootstrapThreePresenter class

fix pagination bug in laravel 5.3

---

resources/views/default/column/editable/checkbox.blade.php

In `datatablesAsync`, if we use `AdminColumnEditable::checkbox` the returned item will have a `data-url` attribute suffixed with `async`,  this URL is not able to post an update request.
also to use `AdminColumnEditable::checkbox` in `datatablesAsync`, we will have to bind a datatable event, in my case I use:
```javascript
$(document).ready(function () {
$('.datatables').on('draw.dt', function() {
$(".inline-editable").editable();
});
});
```

fix AdminColumnEditable ajax url error

---

src/Display/DisplayTable.php

First column has index '0', that was reason for not sortable by first column.

Fix for order by first column

---

src/Display/Column/Control.php

Иногда нужно скрыть кнопки в колонке управления. Например: не нужна кнопка удаления для отображения таблицы в качестве связанной сущности на странице редактирования другой сущности.
```
php
$display = \AdminDisplay::table();
...
$display->getColumns()->getControlColumn()->setDeletable(false);
```

Add custom methods for hide buttons in control column

---

src/Model/SectionModelConfiguration.php

fix error exception
`Class SleepingOwl\Admin\Model\SectionModelConfiguration contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (SleepingOwl\Admin\Contracts\ModelConfiguration  
Interface::setRedirect, SleepingOwl\Admin\Contracts\ModelConfigurationInterface::getRedirect) `

Add Methods setRedirect, getRedirect

---

src/Display/DisplayTable.php

Запустили на миллионных данных. Интерфейс асинхронных DataTables вызывает 1 запрос который запрашивает все данные с таблицы. Так как в этом месте у нас нет модификаций запроса. Ну и собственно cannot allocate memory
Если кто подскажет - буду рад)

Bigdata memory leak issue

---

src/Form/Element/MultiSelect.php
src/Form/Element/NamedFormElement.php

Call to undefined method Illuminate\Database\Query\Builder::getPlainForeignKey()
Исправление названия метода для получения имени ключа, смотри коммит https://github.com/laravel/framework/commit/294c006288ee182eeddf3c6deb23a35032a9219d

Фатальная ошибка при одновременно создании элемента и связанного элемента

---

src/Model/ModelConfigurationManager.php

Используется для поиска нужной секции навигации и добавления в нее элементов меню
```
/**
* Initialize class.
*/
public function initialize()
{
/* @var Page $navigation */
if( $navigation = $this->getNavigationPage('users') ) {
$navigation->addPage(
(new Page(Permission::class))->setIcon('fa fa-group')->setPriority(300)
);
}
}
```

Add getNavigation & getNavigationPage methods

---

src/Form/Element/Number.php

html элемент input с type=number позволяет можно использовать в качестве поля для чисел с плавающей точкой, однако в данном элементе они грубо приводились к целочисленным.

double в input type="number"

---

src/Display/DisplayDatatablesAsync.php

That fix allow to use DisplayDatatablesAsync with different laravel equivalent drivers (at least with jenssegers/mongodb)
Also laravel expected int type for that two methods  https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L1486

[DisplayDatatablesAsync] offset and limit should be int

---

src/Display/Column/Filter.php

Чтобы находясь, например, на десятой странице списка, при нажатии на ссылку-фильтр переходить на первую страницу списка с только что примененным условием фильтрации, а не на десятую, которая может оказаться пустой.
refs #557

Сброс номера страницы при слиянии параметров запроса при фильтрации

---

CHANGELOG.md
src/Form/Element/Images.php

В методе `getValueFromModel()` исправлен парсинг сохраненных ранее изображней как `storeAsComaSeparatedValue()` и парсинг пришедших из формы изображений (если в форме возникла ошибка валидации, они тоже разделены запятой).

Исправлена ошибка парсинга данных изображений.

---

config/sleeping_owl.php
src/Display/Column/DateTime.php
src/Form/Element/DateTime.php
src/Form/Element/Timestamp.php

Кейс: приложение работает в UTC, админы сидят в где-нибудь «там», им удобнее смотреть временные метки в своём часовом поясе.
Добавил возможность указать часовой пояс в конфиге, к которому будут приводиться колонки дат, можно использовать локально с помощью **setTimezone()**:
```php
AdminColumn::datetime('date', 'Date')->setTimezone('Asia/Novosibirsk')->setFormat('d.m.Y')
```
Также с элементом формы DateTime:
```php
AdminFormElement::datetime('date', 'Date')->setTimezone('Asia/Novosibirsk')
```
По элементам формы. При выводе в **parseValue()** дата приводится к часовому поясу админки, при установке значения через **setModelAttrbiute()** приводится к часовому поясу приложения следующим образом:
```php
Carbon::createFromFormat($this->getPickerFormat(), $value, $this->getTimezone()) …
```

Timezone added to the DateTime column type using Carbon's timezone() function

---

src/Display/DisplayTab.php

После коммита https://github.com/LaravelRUS/SleepingOwlAdmin/commit/9011dc6a39855e1959036245ea809e496c2ce37f
Все табы стали активными (по-умолчанию) и их нельзя было из-за этого переключать, у активной же табы было два класса active
```
<li role="presentation" class="active active">
<li role="presentation" class="active">
<li role="presentation" class="active">
```

Отметить активным только реально Активные табы

---

resources/views/default/display/extensions/columns_total.blade.php
src/Display/DisplayTable.php
src/Display/Element.php
src/Display/Extension/ColumnsTotal.php

Добавляет возможность вывести строчку в таблице (DisplayTabble), например, для агрегации результатов:
Пример подключения:
```
$display
->set(
[
Statistic::sum('leads')
],
$display->getColumns()->all()->count()
);
```
Для того, чтобы применить фильтр для текущей query можно сделать следующий запрос:
```
$totalQuery = Statistic::query();
$display->getFilters()->initialize();
$display->getFilters()->modifyQuery($totalQuery);
```
Из **$totalQuery** уже можно скомпоновать агрегированные данные

add columnsTotal extension

---

CHANGELOG.md
resources/views/default/form/element/checkbox.blade.php

Исправлено поведение элемента формы checkbox, теперь оно тоже может быть readonly.

AdminFormElement::checkbox(...)->setReadonly(true)

---

README.md

При установке совы согласно мануала для версии Laravel 5.6 и php 7.2 получаем ошибку:
ReflectionException  : Method SleepingOwl\Admin\Console\Commands\InstallCommand::handle() does not exist
Данная проблема озвучена ранее на форуме: https://laravel.ru/forum/viewtopic.php?id=3447
и протестирована мною лично.

Fix version to install

---

src/Contracts/ModelConfigurationInterface.php
src/Display/Display.php
src/Display/DisplayTree.php
src/Form/FormDefault.php
src/Http/Controllers/AdminController.php
src/Model/ModelConfiguration.php
src/Model/ModelConfigurationManager.php
tests/Admin/Model/ModelConfigurationManagerTest.php
tests/Admin/Model/ModelConfigurationTest.php

- Добавлены пропущенные события `saving`, `saved`
- Убран лишний метод получения объекта [ModelConfiguration](https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/DisplayTree.php#L331)
- Передача объекта записи в метод получения заголовка для страницы редактирования документа. Это позволит в форме редактирования записи использовать заголовок из модели.
- Добавлена возможность передавать в методы создания URL дополнительные параметры. В моей задаче необходимо было добавить в необходимые url, текущий язык записи.
- Изменен (исправлен) порядок вызова событий до сохранения данных в модели. (Желательно этот пункт проверить, т.к. вдруг где-то на этом порядке что либо завязано)

Мелкие исправления.

---

src/Display/DisplayTable.php

При использовании `$this->setControllerClass(class);` в секции, теперь можно в контроллере передавать коллекцию в `onDisplay`.
Для этого в методе 
`getDisplay(ModelConfigurationInterface $model)` 
после 
`$display = $model->fireDisplay(); `
вызываем
`$display->setCollection($my_collection);`

setCollection($collection) in DisplayTable

---

src/Display/Column/OrderByClause.php

Now it work correctly:
`AdminColumn::text('material.title')->setLabel('Название'),`
But it is not:
`AdminColumn::text('material.brand.title')->setLabel('Бренд')`
Let's solve this problem! Load all nested relations in loop via left-join & order by last order field.
👍

Add ability to order DataTables column with nested relations

---

src/Form/Element/NamedFormElement.php
src/Form/Element/Password.php
tests/Admin/Form/Element/NamedFormElementTest.php
tests/Admin/Form/Element/PasswordTest.php

When password field renders value it should be returned only from request, because value from model contains hash of password and should not be rendered at all.

Fix password field completion

---

.travis.yml
resources/views/default/form/element/multiselect.blade.php
src/Contracts/Form/Element/HasSyncCallback.php
src/Contracts/Form/Element/MustDeleteRelatedItem.php
src/Contracts/Form/Element/Taggable.php
src/Factories/FormElementFactory.php
src/Form/Element/MultiDependentSelect.php
src/Form/Element/MultiSelect.php
src/Http/Controllers/FormElementController.php
src/Traits/ElementDeleteRelatedItem.php
src/Traits/ElementSaveRelation.php
src/Traits/ElementSyncCallback.php
src/Traits/ElementTaggable.php

Исправлены ошибки для нового MultiDependentSelect #1003:
**1)** Ошибка 404 при получении зависимого поля через ajax
**2)** Ошибка в названии `multidependselect` исправлено на `multidependentselect`
**3)** Возможности тегирование, коллбек для sync и удаление зависимых сущностей реализованы через traits и interface:
- `\Traits\ElementTaggable` -> `\Contracts\Form\Element\Taggable`
- `\Traits\ElementSyncCallback` -> `\Contracts\Form\Element\HasSyncCallback`
- `\Traits\ElementDeleteRelatedItem` -> `\Contracts\Form\Element\MustDeleteRelatedItem`
**4)** Произведен рефакторинг и удаление дублирующегося кода

fixes for MultiDependentSelect

---

resources/views/default/display/tab.blade.php
src/Display/DisplayTab.php
src/Display/DisplayTabbed.php

Имеем код секции, метод onEdit:
```
public function onEdit($id = null, $payload = [])
{
$model = $id ? \App\Company::find($id) : null;
$tabs = AdminDisplay::tabbed();
$main_form = AdminForm::panel()
->addBody([
AdminFormElement::text('title', 'Название')->required(),
]);
$tabs->appendTab($main_form, 'Основное');
if ($model) {
$model->load('seo');
$payload = ['company_id' => $model->id];
$seo = \AdminSection::getModel(\App\Seo::class);
$seo = $model->seo
? $seo->fireEdit($model->seo->id, $payload)
: $seo->fireCreate($payload)
;
$tabs->appendTab($seo, 'SEO');
}
return $tabs;
```
Данная секция возвращает 2 таба: в первом - простейшая форма редактирования записи о компании, во втором - форма создания или редактирования модели (в зависимости от ее существования) seo-данных записи, которая …

DisplayTab - setId conditions update, DisplayTab external form option, tab title view

---

resources/views/default/display/table.blade.php
resources/views/default/display/tree.blade.php
resources/views/default/form/card.blade.php
resources/views/default/form/card/element.blade.php
src/Contracts/Form/CardInterface.php
src/Contracts/Form/FormFactoryInterface.php
src/Display/DisplayTab.php
src/Display/DisplayTable.php
src/Factories/FormFactory.php
src/Form/Card/Body.php
src/Form/Card/Footer.php
src/Form/Card/Header.php
src/Form/FormCard.php
src/Form/FormTabbed.php
src/Traits/CardControl.php

**Добавлено FormCard (по аналогии с FormPanel)**
Добавлены необходимые классы и дополнены существующие, ничего не сломано
В BS4 panel панель заменено на card, все стили для card (card-header, card-body, card-footer) в пакете уже есть а элемента формы не было.
Просьба почистить переназначение в стилях, прилипает к краям, пропадает отступ
убрать строки 
```
.card-body {
padding: 0 0 1.25em;
}
```
оставить только 
```
.card-body {
flex: 1 1 auto;
padding: 1.25rem;
}
```
по возможности пересмотреть padding, как по мне они лишние
```
.tab-content {
padding-bottom: 1em;
padding-top: 1em;  
}
form .form-buttons {
padding-bottom: 2em;
}
```

added FormCard

---

src/Traits/SqlQueryOperators.php

добавлена возможность при использовании AdminColumnFilter::text()->setOperator('in') вводить значения через запятую для фильтра по массиву
в классе src/Traits/SqlQueryOperators.php метод buildQuery дополнен по аналогии с методом prepareValue

Fix AdminColumnFilter::text()->setOperator('in')

---

src/Traits/MaxFileSizeTrait.php

Возвращает максимальный размер загружаемого файла из конфигурации php.ini в **килобайтах**.
Ранее возвращаемое значение конвертировалось в **мегабайтах**, в результате чего при указании ограничения в maxSize($size) по итогу сравнивалось значение в килобайтах со значением максимального размера загружаемого файла из конфигурации php.ini в мегабайтах, что приводило к ошибке при загрузке изображения (-ий).

Fix значение файла из php.ini конвертируем в килобайты

---

src/Http/Controllers/FormElementController.php

If model has some $primaryKey value different from 'id', selectajax form element has unselectable items because of null value of id field of json answer from backend. For example: [{"tag_name":"BOSCH (id=3)","id":null,"custom_name":null},{"tag_name":"BOSCH \u0411\u044b\u0442\u043e\u0432\u0430\u044f \u0442\u0435\u0445\u043d\u0438\u043a\u0430 (id=646)","id":null,"custom_name":null},{"tag_name":"BOSCH \u0410\u0432\u0442\u043e\u0442\u043e\u0432\u0430\u0440\u044b (id=1301)","id":null,"custom_name":null},{"tag_name":"BOSCH PETFOOD (id=1845)","id":null,"custom_name":null}]
With fix from this PR problem is solved, json is like [{"tag_name":"BOSCH (id=3)","id":3,"custom_name":null},{"tag_name":"BOSCH \u0411\u044b\u0442\u043e\u0432\u0430\u044f \u0442\u0435\u0445\u043d\u0438\u043a\u0430 …

Fix for case when primary key field name is other than 'id'.

---

src/Providers/AdminServiceProvider.php

Fixed PHP 8 error "Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero"

Fix sorting

---

src/Form/Element/NamedFormElement.php
src/Form/FormDefault.php
tests/Admin/Form/Element/NamedFormElementTest.php

Изменения
В `NamedFormElement.php` последнюю часть после . считаю всегда названием поля и отбрасываю ее при помощи array_pop, по всем остальным прохожусь циклом и падаю с ошибкой если не получается какую-нибудь из связей разрезолвить.
При сохранении вызываю `saveBelongsToRelations` и `saveHasOneRelations` рекурсивно для всех моделей. Скорее всего не будет работать при `->hasOne->belongsTo`, когда belongsTo еще не создана
В тестах:
Этот код теперь выбрасывает исключение (так как ожидается что `key` вернет модель). Его перенес в 
метод `test_get_model_by_path_exception`
```php
$element->setModel($model = m::mock(\Illuminate\Database\Eloquent\Model::class));
$model->shouldReceive('getAttribute')->with('key')->andReturn('test');
$this->assertNull($this->callMethodByPath($element, …
```

feat: add ability to save nested level of relations

---

src/Form/Element/NamedFormElement.php

Если у Select стоит json-поле, не работает установка значения по умолчанию.
Пример:
```php
AdminFormElement::select('setting_parsing->currency', 'Исходная валюта')
->setOptions([
'RUB' => 'RUB',
'USD' =>'USD',
])
->setDefaultValue('RUB')
```

fix(element): set default value for select with json field

---

src/Display/Column/Filter/DateRange.php

Old behavior: filter adds interval '0000-00-00' - '9999-12-31' by default, so, null isn't in this range and rows with null-value in filtered field is out of query result.
But if user didn't choose any date, they don't care about value necessity, value might be null, less than 0000-00-00 etc.
New behavior: until user chooses smth in filter, it won't be applied to DB query.

Date range filter works fine with nullable fields now.

---

src/Http/Controllers/AdminController.php

Речь про AdminColumnEditable. При inline редактировании сова ищет необходимый столбец, но когда его не находит не останавливается и продолжает искать его на следующих табах, из-за чего по итогу он может сбиться.
Исправил тем, что останавливаю перебор в случае нахождения столбца.

fix(inline-edit): if column is found, stop searching
