src/Templates/TemplateDefault.php
added flow.js and sortable js libs to Meta::loadPackage. Since i was getting error
on console relative to both libs and image multi upload was not working until i've added flow.js lib to package.
=> Added missing libs to Meta Package

src/Form/Element/Select.php
Select always is sorting options. I need unsortable select. I added new property - sortable.
=> Sortable property for Select.

README.md, resources/views/default/form/element/date.blade.php, resources/views/default/form/element/password.blade.php, resources/views/default/form/element/text.blade.php, resources/views/default/form/element/textarea.blade.php, resources/views/default/form/element/time.blade.php, resources/views/default/form/element/timestamp.blade.php, src/Form/Element/NamedFormElement.php, src/Form/Element/Text.php, src/Form/FormElement.php
BTW, I probably won't PR so often in nearest future. Will try to ammass the code beforehand.
=> Hotfixes and refactoring.

src/Form/FormDefault.php
$relation can be a collection not only a array, saveMany accept a Traversable or array, method saveHasOneRelations should take this in account.
=> fix saveHasOneRelations when relation is a Collection

README.md
=> Add instructions for L5.1

resources/views/default/display/tree_children.blade.php, src/Display/DisplayTree.php
I will add example of usage to docs and demo app.
=> Allow to use callable as value for tree admin display.

src/Form/Element/NamedFormElement.php
Поправил. Проверил, создание, изменение с BelongsTo работает #213.
=> Vaiil patch 1

src/Display/DisplayTree.php
There was error «trying to call isEditable() on null». Fixed it.
=> Feature/di: fixed DisplayTree component

src/Http/Controllers/AdminController.php
#263 Not fixed.
We still have problems with route:list command and breadcrumbs.
Need Check for existence of breadcrumbs before registering it in AdminController.
=> Fix problem with `route:list`

src/Http/Controllers/AdminController.php
Done this to preserve context, when using model with tabs and fireDisplay
=> Pass model form input on Save&Create action

src/Form/Element/MultiSelect.php
Хвала небесам, смог написать pull request.
=> fix multiselect disabled attribute

src/Model/ModelConfiguration.php
in `app/Admin/SomeModel.php` add `$model->setDeletable(false);` can create non-deletable model
=> make deletable customizable

src/Display/DisplayTree.php
Fixing behavior using AdminDisplay::tree().
Issue #309 & #311
=> Fix for AdminDisplay::tree() #309 & #311

resources/views/default/_partials/header.blade.php
http://i82.fastpic.ru/big/2016/1026/5c/c2200ec45f716743eaf2a86fd3cffe5c.jpg
=> Fix layout

resources/views/default/form/element/number.blade.php, src/Facades/FormElement.php, src/Form/Element/Number.php, src/Providers/AliasesServiceProvider.php
Form element using native input number element.
Methods: setMin, setMax, setStep.
Already tested http://joxi.ru/E2p9eoXc01G1AY
=> Make number form element

src/Form/Element/Number.php
I caught an error with saving empty string to the numeric database column. Here is solution. Thanks.
=> fix saving empty string to numeric column

src/Display/DisplayDatatablesAsync.php
Фиксю твои кнопки для Datatables
=> Fix DatatablesAsync buttons

src/Display/ControlLink.php
Мысль я думаю поймешь направь как правильней это будет в итоге.
=> Development for SetAttributesCondition

src/Display/ControlLink.php
Ставим нужные классы, тайтлы,(прочие ипучие атрибуты) в зависимости от данных модели) 
C уважением Ваш покорный.
=> Set Fix to Html Condition Attributes

src/Display/Column/Control.php
Исправил ошибку при отображении кнопки "восстановить" в таблице на удаленной записи
=> Fix get restore url in Control.php

resources/views/default/display/extensions/columns_async.blade.php
To work placement filters on top table
=> add table.header position to column_async

src/Display/TableColumn.php
#356 Fix Message and way to transform array
=> Send model to all views attached with setView

resources/views/default/column/checkbox.blade.php, resources/views/default/column/count.blade.php, resources/views/default/column/editable/checkbox.blade.php, resources/views/default/column/url.blade.php, src/Display/Column/Count.php, src/Display/Column/Custom.php, src/Display/Column/DateTime.php, src/Display/Column/Email.php, src/Display/Column/Image.php, src/Display/Column/Link.php, src/Display/Column/Text.php, src/Display/TableColumn.php
=> Column appendable refactored

resources/views/default/display/extensions/columns_async.blade.php
=> Fix for filters sorting position

src/Contracts/Form/FormElementInterface.php, src/Display/DisplayTab.php, src/Display/DisplayTabbed.php, src/Form/Element/NamedFormElement.php, src/Form/FormElement.php, tests/Admin/Form/Element/NamedFormElementTest.php, tests/Admin/Form/FormElementTest.php
=> Добавление метода проверки isValueSkipped в NamedFormElement

src/Form/Element/NamedFormElement.php
Возможность делать setDefaultValue для полей которых нет у модели и если поле null or empty
=> setDefaultValue works for fields with model

src/Form/Buttons/Cancel.php
```
* Добавлен метод getCancelUrl для установки Url кнопки Отмены
```
Fix #523
=> Fix getCancelUrl

resources/lang/ru/lang.php
Добавлен русский язык для кнопки фильтрации.
=> Add russian translite of button in filter

src/Display/Column/Editable/Text.php, src/Factories/DisplayColumnEditableFactory.php
=> Feature new Editable Colunm Text

src/Display/Column/Filter.php
=> Fix filter parameters merging

src/Display/Column/Editable/Text.php
HotFix AdminColumnEditable Text
=> HotFix AdminColumnEditable Text

CHANGELOG.md, src/Display/Column/Editable/Checkbox.php, src/Display/Column/Editable/Text.php
Метки полей, заданные конструктором не выводятся в таблице.
=> Не выводятся метки полей для редактируемых колонок.

src/Console/Commands/UserManagerCommand.php, src/Display/Column/Filter/Date.php, src/Display/Filter/FilterRelated.php, src/Form/Element/DateTime.php, src/Http/Controllers/DisplayController.php
In cases like #597 this pull request might help a lot.
=> Added logging of caught exceptions where it makes sense

resources/views/default/column/editable/select2.blade.php, resources/views/default/column/editable/textarea.blade.php, src/Display/Column/Editable/Select2.php, src/Display/Column/Editable/Textarea.php, src/Factories/DisplayColumnEditableFactory.php
Feature Add Editable Columns Textarea & Select2
=> Feature Add Editable Columns Textarea & Select2

resources/views/default/column/editable/select.blade.php
=> Feature Select Editable

CHANGELOG.md
Feature AdminColumnEditable::select
=> Feature AdminColumnEditable::select

src/Navigation.php
При создание новой записи отсутствует ключ "adminModelId", так как данный ключ не где более не запрашивается логичнее проверять на существование другой ключ "adminModel"
=>  Fixed #705

resources/views/default/form/button.blade.php, src/Form/Buttons/Cancel.php, src/Form/Buttons/Delete.php, src/Form/Buttons/Destroy.php, src/Form/Buttons/Restore.php, src/Form/Buttons/Save.php, src/Form/Buttons/SaveAndClose.php, src/Form/Buttons/SaveAndCreate.php
Было:
- невозможно добавить класс или стили к кнопке Cancel
- в описаниях классов кнопок копипасты из "Save" или "Cancel" 
Стало:
- setHtmlAttributes работает для AdminFormButton::cancel()
- описания классов кнопок соответствуют их названиям
=> Fixes in buttons

resources/views/default/column/editable/datetime.blade.php
=> fix viewformat for datetime editable

resources/views/default/form/element/select.blade.php, src/Form/Element/Select.php
fixed #737  Problem with AdminFormElement::select
=> fixed #737 Problem with AdminFormElement::select

CHANGELOG.md, resources/views/default/column/link.blade.php, resources/views/default/column/text.blade.php, src/Display/Column/NamedColumn.php, src/Display/Column/RelatedLink.php, src/Display/Column/Text.php, src/Display/Column/Url.php
Как-то так. думаю облегчит немного секции людям от кастомов
=> Добавление третьего параметра

resources/assets/less/libs/dataTables.less
=> Fix view datatables CSS

resources/views/default/column/count.blade.php, resources/views/default/column/custom.blade.php, resources/views/default/column/datetime.blade.php, resources/views/default/column/email.blade.php, resources/views/default/column/text.blade.php
Не применялись Html атрибуты для колонок внутри display.
Не было нужного атрибута в шаблонах типов данных.
Обернул данные в div и добавляю им html атрибуты
=> Не работали setHtmlAttribute

src/Form/Element/Image.php
Валидатор не пропускал SVG файлы. Теперь сможет
=> Fix SVG Validator

src/Facades/FormElement.php
=> Add to FormElement Facades DependentSelect

src/Form/FormElement.php
=> Validation by Rule objects in sections

src/Model/ModelConfigurationManager.php
Поправил метод для обратной совместимости при апдейте
=> Fix getEditTitle

src/Contracts/ModelConfigurationInterface.php
=> Fix error Declaration getEditTitle

src/Contracts/Display/ColumnInterface.php, src/Display/DisplayDatatables.php, src/Display/TableColumn.php
Add visible property and isVisible, setVisible methods to control column visibility. It let to use search an filters with out display column
=> Fuature display column add visibility

config/sleeping_owl.php
=> Чтоб кедитор не удалял классы

src/Form/Columns/Column.php, src/Form/Columns/Columns.php
Add ability to set width of the Column for each of the Bootstrap screen sizes: xs, sm, md, lg
=> Column width

resources/views/default/column/control.blade.php, src/Display/Column/Control.php
Очень не хватает возможности добавить, например, style="white-space:nowrap" к блоку кнопок при добавлении своей кнопки:
```
$button = (new ControlLink(function ($model) {
return route('admin.model', ['car_models', 'brand_id' => $model->id]);
}, function ($model) {
return $model->models_count;
}, 100))
->setTitle(function ($model) {
return 'Кол-во моделей: ' . $model->models_count;
})
->setIcon('fa fa-car')
->setHtmlAttribute('class', 'btn-warning')
->setCondition(function () {
return true;
})
;
$display->getColumns()->getControlColumn()
->addButton($button)
->setHtmlAttribute('style', 'white-space:nowrap')
;
```
Запилил реализацию, странно что ее не было изначально.
=> Add ability to apply html attributes to the Control Column

resources/views/default/_partials/navigation/badge.blade.php
Очень напрягает сияющий 0 возле кнопки аля "Жалобы". Нет жалоб - нечего и показываться, am I right?
=> Make navigation badges hideable 

src/Model/ModelConfigurationManager.php
=> Laravel 5.8 and 5.4 support

resources/views/default/form/tabbed.blade.php
fix "syntax error, unexpected '@'" and refactoring hardcode in tab template
=> fix tab template

CHANGELOG.md
Feature from pull:
https://github.com/LaravelRUS/SleepingOwlAdmin/pull/1003
=> Changelog feature - MultiDependentSelect

src/Console/Commands/stubs/section.stub
=> fix: pass quotes

src/Form/Element/DependentSelect.php
Added processing nullable scenario to render method to DependentSelect. Closing #1126
=> fixed problem in issue #1126

resources/views/default/display/tabbed.blade.php
=> Fix tabs container

src/Http/routes.php, src/Providers/AdminServiceProvider.php
Delete double route names for laravel 7 support
=> Laravel 7 routes name fix

CHANGELOG.md, src/Display/Column/Editable/Checkbox.php, src/Display/Column/Editable/DateTime.php, src/Display/Column/Editable/Number.php, src/Display/Column/Editable/Select.php, src/Display/Column/Editable/Text.php, src/Display/Column/Editable/Textarea.php
Fixed fields:
Checkbox, datetime, number, select, text & textarea
=> Fixin` editables editing values by relation

src/Form/Element/NamedFormElement.php, tests/Admin/Form/Element/NamedFormElementTest.php
Problem fix + code cleanup + tests update.
=> Fix for unique validation of field for model with primary case different from default 'id'.

src/Form/Element/NamedFormElement.php
Добавил недостающий перевод в aссоциативный массив и упростил условия проверки
=> Bugfix decode json field

src/Display/Column/RelatedLink.php
Описал проблему в ТГ чате - https://t.me/sleeping_owl/11889
=> fix: related link
